# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{resque-multi-job-forks}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Mick Staugaard"]
  s.date = %q{2010-12-17}
  s.description = %q{When your resque jobs are frequent and fast,
      the overhead of forking and running your after_fork might get too big.}
  s.email = %q{mick@staugaard.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "lib/resque-multi-job-forks.rb",
    "resque-multi-job-forks.gemspec",
    "test/helper.rb",
    "test/test_resque-multi-job-forks.rb"
  ]
  s.homepage = %q{http://github.com/staugaard/resque-multi-job-forks}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Have your resque workers process more that one job}
  s.test_files = [
    "test/helper.rb",
    "test/test_resque-multi-job-forks.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<resque>, [">= 1.6.0"])
    else
      s.add_dependency(%q<resque>, [">= 1.6.0"])
    end
  else
    s.add_dependency(%q<resque>, [">= 1.6.0"])
  end
end

